from __future__ import annotations
import asyncio
import json
import time
from rich.console import Console
from agents import Runner, RunResult

# Import agents and data loader
from .mining_agents_core.environment_agent import environment_agent, EnvironmentAgentOutput
from .mining_agents_core.equipment_agent import equipment_agent, EquipmentAgentOutput
from .mining_agents_core.logistics_agent import logistics_agent, LogisticsAgentOutput
from .mining_agents_core.optimizer_agent import optimizer_agent, OptimizerAgentOutput
from .data_loader import get_all_forecast_data
from .printer import Printer

class MiningOperationManager:
    """
    Orchestrates the full flow: data loading, specialist analysis, 
    and final optimization.
    """

    def __init__(self) -> None:
        self.console = Console()
        self.printer = Printer(self.console)

    async def run(self) -> None:
        """
        Executes the entire mining value chain analysis and optimization workflow.
        """
        overall_start_time = time.time()
        self.printer.update_item("start", "Starting Mining Value Chain Analysis...", is_done=False)
        
        # 1. Load all necessary data
        self.printer.update_item("data_loading", "Loading forecast and operational data...", is_done=False)
        all_data = get_all_forecast_data()
        self.printer.mark_item_done("data_loading")

        # 2. Run specialist agents concurrently
        self.printer.update_item("analysis", "Running specialist agents (Environment, Equipment, Logistics)...", is_done=False)
        analysis_start_time = time.time()
        
        env_task = self._run_environment_analysis(all_data["weather"], all_data["road"])
        equip_task = self._run_equipment_analysis(all_data["equipment"])
        log_task = self._run_logistics_analysis(all_data["vessel"], all_data["logistics"])

        results = await asyncio.gather(env_task, equip_task, log_task)
        
        analysis_duration = time.time() - analysis_start_time
        self.printer.update_item("analysis", f"Specialist analysis complete in {analysis_duration:.2f} seconds.", is_done=True)
        
        env_output, equip_output, log_output = results

        # 3. Run the optimizer agent with the collected insights
        if all(results):
            self.printer.update_item("optimization", "Synthesizing insights and generating recommendations...", is_done=False)
            optimization_start_time = time.time()
            
            final_recommendations = await self._run_optimization(env_output, equip_output, log_output)
            
            optimization_duration = time.time() - optimization_start_time
            self.printer.update_item("optimization", f"Optimization complete in {optimization_duration:.2f} seconds.", is_done=True)

            self.printer.update_item("complete", "Analysis complete.", is_done=True)
            self.printer.end()

            # 4. Print the final report
            print("\n\n" + "="*20 + " MINING OPERATIONS WEEKLY PLAN " + "="*20 + "\n")
            print("Generated by AI Agent System\n")
            
            if final_recommendations:
                print("--- Recommended Actions ---\n")
                for rec in final_recommendations.recommendations:
                    print(f"🔵 Scenario: {rec.scenario}")
                    print(f"   Priority: {rec.priority}")
                    print(f"   Justification: {rec.justification}\n")
                
                print("\n" + "--- Draft Email for Weekly Plan ---\n")
                print(final_recommendations.weekly_email_plan)
            else:
                print("Could not generate recommendations.")
        else:
            self.printer.update_item("analysis", "Failed to get results from one or more specialist agents.", is_done=True, hide_checkmark=True)
            self.printer.end()

        overall_duration = time.time() - overall_start_time
        print(f"\n--- Total Execution Time: {overall_duration:.2f} seconds ---")
        print("\n" + "="*68 + "\n")


    async def _run_environment_analysis(self, weather_data, road_data) -> EnvironmentAgentOutput | None:
        try:
            data_payload = {"weather_data": weather_data, "road_data": road_data}
            prompt = f"Analyze the provided environmental data. Data: {json.dumps(data_payload)}"
            result = await Runner.run(environment_agent, prompt)
            return result.final_output_as(EnvironmentAgentOutput)
        except Exception as e:
            self.console.print(f"[bold red]Error in Environment Agent:[/bold red] {e}")
            return None

    async def _run_equipment_analysis(self, equipment_data) -> EquipmentAgentOutput | None:
        try:
            data_payload = {"equipment_data": equipment_data}
            prompt = f"Analyze the provided equipment data. Data: {json.dumps(data_payload)}"
            result = await Runner.run(equipment_agent, prompt)
            return result.final_output_as(EquipmentAgentOutput)
        except Exception as e:
            self.console.print(f"[bold red]Error in Equipment Agent:[/bold red] {e}")
            return None

    async def _run_logistics_analysis(self, vessel_data, logistics_data) -> LogisticsAgentOutput | None:
        try:
            data_payload = {"vessel_data": vessel_data, "logistics_data": logistics_data}
            prompt = f"Analyze the provided logistics and vessel data. Data: {json.dumps(data_payload)}"
            result = await Runner.run(logistics_agent, prompt)
            return result.final_output_as(LogisticsAgentOutput)
        except Exception as e:
            self.console.print(f"[bold red]Error in Logistics Agent:[/bold red] {e}")
            return None

    async def _run_optimization(
        self, 
        env_output: EnvironmentAgentOutput, 
        equip_output: EquipmentAgentOutput, 
        log_output: LogisticsAgentOutput
    ) -> OptimizerAgentOutput | None:
        try:
            # Ensure summaries are not None before formatting
            env_summary = env_output.environment_summary if env_output else "Not available"
            equip_summary = equip_output.equipment_summary if equip_output else "Not available"
            log_summary = log_output.logistics_summary if log_output else "Not available"

            input_prompt = f"""
            Here are the summaries from the specialist agents:

            - **Environment Summary**: {env_summary}
            - **Equipment Summary**: {equip_summary}
            - **Logistics Summary**: {log_summary}

            Based on these, generate optimization scenarios and a weekly plan by calling the appropriate tool with these summaries.
            """
            
            result = await Runner.run(optimizer_agent, input_prompt)
            return result.final_output_as(OptimizerAgentOutput)
        except Exception as e:
            self.console.print(f"[bold red]Error in Optimizer Agent:[/bold red] {e}")
            return None
